spring:
  profiles:
    # Bellow active attribute can be used for testing
    #active: "postgres"
    active: "cassandra"
  main:
    banner-mode: "console"

server:
  port: 9081
  servlet.contextPath: /citizen-service

---

spring:
  profiles: postgres
  banner.location: banner-postgres.txt
  jpa:
    database: POSTGRESQL
    show-sql: false
    driverClassName: org.postgresql.Driver
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: false
    hibernate.ddl-auto: none
    hibernate.show-sql: false
    hibernate.database: postgresql
    hibernate.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.open-in-view: false
    hibernate.generate-ddl: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testdb2
    username: postgres
    password: postgres
    testWhileIdle: true
    validationQuery: "SELECT 1"

---
spring:
  profiles: cassandra
  banner.location: banner-cassandra.txt
  data.cassandra.keyspace-name: my_cassandra_test
  data.cassandra.contact-points: 127.0.0.1
  data.cassandra.port: 9042




